package.json
src/views/examples/analysis/MapAnalysis.js

[Fix] 강민지 작업공간 개선

---

src/views/examples/chatBot/chatBotPage.js

[Fix] 질문 생성 부분 로직 원상복귀

---

src/views/examples/chatBot/chatBotPage.js

챗봇 코드에서 입력 값 받는 부분 지정 값에서 userInput으로 수정하고, 입력 값이 수정일 때의 로직 살짝 추가했어요. 생성 부분에서 에러가 안 잡혀서 확인 부탁드립니다!

[Feat] 챗봇 코드 수정 및 추가

---

src/views/IndexSections/record copy.js
src/views/IndexSections/record.js
src/views/examples/Profile copy.js
src/views/examples/chatBot/chatBotPage.js

성적 폼 & 입력 추가 성적 업데이트 및 수정 기능 구현 중

[Feat] 마이페이지 성적 폼 & 입력 추가

---

src/views/IndexSections/record.js

[Feat] 성적 데이터 삽입 & 불러오기 함수 구현

---

src/views/examples/analysis/FullAnal.css
src/views/examples/analysis/FullAnal.js
src/views/examples/analysis/FullAnalysis.js

전체 분석 페이지 초기 버전입니다! 확인 부탁드려요! 수정 버전은 추후 작업해서 pr 요청할게요!

[Feat] 전체 분석 페이지 작성

---

src/views/examples/analysis/FullAnal.css
src/views/examples/analysis/FullAnal.js
src/views/examples/analysis/FullAnalysis.js

- 내 성적 옆에 희망 학과 칸 추가
- 한 페이지에 보여지는 데이터 수를 4개에서 10개로 수정 (스크롤로 내리면서 확인 가능)
- 페이지 아래 쪽 부분의 화살표 사이에 페이지 표시 기능 추가
- 위험일 경우에만 프로그레스바의 합격률 글자가 검정색으로 나오도록 수정
- FullAnalysis.js의 불필요한 부분 삭제

[Fix] 전체 분석 페이지 피드백 반영 수정

---

src/views/examples/chatBot/chatBotPage.js

챗봇 자기소개서 생성 버그 수정 length 오류 해결
수정 등 추가 x

[Fix] 챗봇 수정

---

src/contexts/AuthContext.js
src/views/examples/Profile.js

세션 적용 안 되던 버그 수정
세션 가용성 개선
세션 만료 로직 추가 30분마다 만료

[Fix] 세션 버그 수정

---

src/views/examples/chatBot/chatBotPage.js

- 작업 내용 -
1. 챗봇 자기소개서 수정 부분 질문 띄워주는 작업 완료 (수정된 자기소개서 생성하는 부분은 백엔드 작업 후 상세히 구현 예정, 현재 유저 응답 모으는 부분에서 수정 입력한 부분까지 모아버려서 추후 수정 예정)
2. 챗봇 자기소개서 수정 부분 서버 연결 작업 진행 중 (백엔드 쪽 구현 진행하면서 프론트에서도 추후 자세히 진행 예정)

[Feat] 챗봇 자기소개서 수정 구현 코드 추가 및 수정

---

package.json
src/views/examples/analysis/FullAnal.css
src/views/examples/analysis/FullAnal.js
src/views/examples/chatBot/chatBotPage.js

- 작업 내용 -
1. 여유, 적절, 도전, 위험 글자 색을 프로그레스 바 색상과 동일하게 수정
2. 테스트용으로 예시 데이터 좀 더 추가

[Fix] 전체 분석 페이지 피드백 반영한 수정 (글자 색 변경)

---

src/views/examples/analysis/SearchBar.js
src/views/examples/analysis/UMap.js
src/views/examples/analysis/map_data.json
src/views/examples/analysis/test_user_data.json

- 화면 3:7로 분할 후 왼쪽에 검색 창 생성(검색창 js파일 따로 생성)
- 원하는 학교 검색하면 해당 학교로 지도 마커 이동

[feat] 검색창 생성 및 검색 기능 구현

---

src/views/examples/chatBot/chatBotPage.js
src/views/examples/chatBot/modal.css
src/views/examples/chatBot/modal.js

- 작업 내용 -
1. 챗봇 자기소개서 수정 부분 잘 생성되도록 코드 보완 (일부 코드 누락 문제 -> 올바르게 실행되도록 수정 완료)
2. 자기소개서 생성 및 수정 시 모달창 문구 일관되게 변경

[Fix] 챗봇 자기소개서 수정 부분 오류 해결

---

src/views/examples/chatBot/chatBotPage.js

- 예외 처리 작업 내용 -
1. '생성' or '수정' 입력
2. 1 or 2 번호 입력

[feat] 챗봇 예외처리 부분 추가

---

src/views/examples/analysis/Full/FullAnal.css
src/views/examples/analysis/Full/FullAnal.js
src/views/examples/analysis/Full/SearchComponent.js

- 작업 내용 -
1. 전체 분석 화면 너비 가운데 정렬이 되도록 수정
2. 검색 컴포넌트 분리 (맞게 된지는 확인 필요)

[Fix] 전체 분석 화면 너비 수정 및 검색 컴포넌트 분리 작업

---

src/views/examples/analysis/Full/FullAnal.css

[Fix] 전체 분석 화면 너비 조정

---

src/views/examples/analysis/Full/FullAnal.js
src/views/examples/analysis/Full/SearchComponent.js

- 작업 내용 -
1. 콤보박스 선택 값에 따라 콤보박스 크기 변하지 않도록 고정
2. 콤보박스 내에서 X 버튼 누르면 에러 안 뜨게 경우에 따라 상태 처리

[Fix] 전체 분석 콤보박스 크기 고정 및 X 누를 때 상태 처리

---

package.json
src/contexts/AuthContext.js
src/setupProxy.js
src/views/IndexSections/record.js
src/views/examples/Landing.js
src/views/examples/Login.js
src/views/examples/Profile.js
src/views/examples/analysis/IntensiveAnalysis/Search.js
src/views/examples/chatBot/chatBotPage.js

마이페이지 성적 추가 & 성적 조회 & 교과목 조회 기능 추가
세션 방식 로컬스토리지 -> 쿠키로 변경
그에 따른 변화 proxy 형태로 url 요청
url 요청시 챗봇 서버 -> /api/8582 -> /api로 인식
spring 서버(챗봇 제외 전부) -> /api/8482를 붙이면 /api로 인식
즉, /api/8482/score -> /api/score로 인식
도메인 및 포트번호 자동 바인딩 되도록 설계
http~ orion 이런 거 안 적고 그냥 /api부터만 적으면 됨ㅇㅇ
추가 적으로 쿠키 방식 채용했기 때문에 npm install js-cookie 하셔야 합니다.

[Feat] 세션 방식 변경 및 api 요청 방식 변경 & 마이페이지 기능 추가

---

package.json
src/setupProxy.js
src/views/IndexSections/record.js
src/views/examples/analysis/IntensiveAnalysis/Search.js

집중분석 페이지 구현 완료
ai 서버 proxy 작업 완료
ai 서버 500에러
내가 알기론 하스팟으로만 가능했던 걸로 기억... 이러면 어떻게 보여주지?

[Feat] 집중분석 구현

---

src/views/examples/analysis/Full/FullAnal.css
src/views/examples/analysis/Full/FullAnal.js

- 작업 내용 -
1. 여유 적절 안전 도전 버튼 색상 변경
2. 학교 로고 보이도록 추가

[Fix] 전체 분석 버튼 색상 수정 및 로고 추가

---

src/views/examples/analysis/Full/FullAnal.js

- 작업 내용-
전체분석에서 계열을 선택하면 해당 계열에 포함되는 모든 학과 목록이 뜨도록 수정

[Fix] 전체분석 계열 선택 시 학과 목록 뜨게 하기

---

src/views/examples/analysis/Full/FullAnal.js

- 작업 내용 -
1. 서버 요청 코드 추가 (fetch 구문으로)
2. 변수 일부 수정 (api 형식에 맞게)

[Feat] 서버 요청 코드 추가

---

src/views/examples/analysis/Full/FullAnal.css
src/views/examples/analysis/Full/FullAnal.js
src/views/examples/analysis/Full/FullAnalModal.css
src/views/examples/analysis/Full/FullAnalModal.js

- 작업 내용
1. 로딩 중일 때는 로딩 모달창, 로딩이 끝나면 분석 완료 모달창이 뜨도록 함.
2. 여유, 적절, 도전, 위험 중 해당 데이터가 없을 경우 알림창으로 안내할 수 있도록 추가

[Feat] 전체분석 모달창 및 알림창 추가, 기능 개선

---

src/views/examples/analysis/Full/FullAnal.js

전체분석 -> 검색 시 데이터가 존재할 경우 자동으로 해당 페이지 조회

[Feat] 데이터 있을 경우 자동 조회
